name: rastrobus
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_loggy_dio: ^3.1.0
  flutter_osm_plugin: ^1.2.0
  google_fonts: ^6.2.1
  json_annotation: ^4.9.0
  provider: ^6.1.2
  retrofit: ^4.4.1
  geolocator: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  retrofit_generator: ^9.1.2
  build_runner: ^2.4.13
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
